# Generated by Django 3.1.2 on 2020-11-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_liks',
            new_name='user_likes',
        ),
    ]
