# Generated by Django 3.1.2 on 2020-11-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201105_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_likes',
            new_name='user_like',
        ),
    ]
